#docker-compose.yml
version: '3.8'

services:

  # Frontend React/Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${VITE_PORT}:80"
    networks:
      - efrei-fullstack-js-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - efrei-fullstack-js-network

# Réseau pour la communication entre conteneurs
networks:
  efrei-fullstack-js-network:
    driver: bridge
