version: '3.8'

services:
  frontend:
    container_name: fullstack-js-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_ENV_MODE=${VITE_ENV_MODE}
        - VITE_PROTOCOL_API=${VITE_PROTOCOL_API}
        - VITE_HOST_API=${VITE_HOST_API}
        - VITE_PORT_API=${VITE_PORT_API}
        #- VITE_API_URL=${VITE_API_URL}
        - VITE_PROTOCOL=${VITE_PROTOCOL}
        - VITE_HOST=${VITE_HOST}
        - VITE_PORT=${VITE_PORT}
    ports:
      - "${VITE_PORT}:80"  # Nginx écoute sur le port 80
    environment:
      - NODE_ENV=${VITE_ENV_MODE}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  backend:
    container_name: fullstack-js-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT_API}:3300"
    environment:
      - NODE_ENV=${VITE_ENV_MODE}
    volumes:
      - ./backend:/app
      - ./.env:/.env
